language: common-lisp

sudo: false

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - LD_LIBRARY_PATH=$HOME/libuv/lib:$HOME/libfixposix/lib:$LD_LIBRARY_PATH
    - C_INCLUDE_PATH=$HOME/libuv/include:$HOME/libfixposix/include:$C_INCLUDE_PATH
    - CPLUS_INCLUDE_PATH=$C_INCLUDE_PATH
    - ROSWELL_BRANCH=release
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin

addons:
  apt:
    packages:
      - nodejs

install:
  # libuv for Wookie
  - if ! [ -f "$HOME/libuv/include/uv.h" ]; then ./t/install-libuv.sh; fi
  # libfixposix for IOLib
  - if ! [ -f "$HOME/libfixposix/include/lfp.h" ]; then ./t/install-libfixposix.sh; fi
  # Install Roswell
  - if ! $(which ros >/dev/null); then
      curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh;
    fi
  - npm install ws
  - mkdir -p ~/common-lisp
  - git clone https://github.com/fukamachi/clack ~/common-lisp/clack
  - git clone https://github.com/fukamachi/fast-websocket ~/common-lisp/fast-websocket

cache:
  directories:
    - $HOME/.roswell
    - $HOME/libfixposix
    - $HOME/libuv
    - $HOME/.config/common-lisp

script:
  - ./run-tests.sh
