language: common-lisp

sudo: false

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - LD_LIBRARY_PATH=$HOME/libuv/lib:$HOME/libfixposix/lib:$LD_LIBRARY_PATH
    - C_INCLUDE_PATH=$HOME/libuv/include:$HOME/libfixposix/include:$C_INCLUDE_PATH
    - CPLUS_INCLUDE_PATH=$C_INCLUDE_PATH
    - ROSWELL_BRANCH=release
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin

addons:
  apt:
    packages:
      - nodejs

install:
  # libuv for Wookie
  - curl -L https://github.com/libuv/libuv/archive/v1.6.1.tar.gz | tar xzf -
  - (cd libuv-1.6.1 && ./autogen.sh && ./configure --prefix=$HOME/libuv && make && make install)
  # libfixposix for IOLib
  - curl -L https://github.com/sionescu/libfixposix/archive/v0.3.0.tar.gz | tar xzf -
  - (cd libfixposix-0.3.0 && autoreconf -i -f)
  - (cd libfixposix-0.3.0 && mkdir build/ && cd build/ && ../configure --prefix=$HOME/libfixposix && make && make install)
  # Install Roswell
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - npm install ws
  - git clone -b clack-socket https://github.com/fukamachi/clack ~/lisp/clack

cache:
  directories:
    - $HOME/.roswell

script:
  - ./run-tests.sh
